[package]
name = "pdl"
version = "0.1.0"
authors = ["Shunichi Ikegami <sike.tm@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0.1"
clap = "2.33.3"
url = "2.2.2"
